version: '3.7'

services:

# flask:

  redis:
  # This image is based on Debian
  # there is also an image based on Alpine but it uses an older Redis release.
    image: redis:latest
    env_file: docker.env
    ports:
      - "6379:6379"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 15s

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
#      start_period: 30s

