version: '3.7'

# Starts these services:
#   redis, a message queue and in-memory database
#   webapp, a web app implemented with flask; see port 5001
#   worker, where celery taske run
#   monitor, celery 'flower', a web app to monitor celery; see port 5555

services:
  redis:
  # This image is based on Debian;
  # there is an image based on Alpine but it uses an old Redis release.
    image: redis:latest
#    env_file: docker.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 15s
    networks:
      default:
        aliases:
          - redis

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.accela-flask
    image: wildsong/accela-flask:latest
#    env_file: .env
    environment:
      - PYTHONPATH=/srv
      - FLASK_APP=start_app
      # without these, flask app cannot find redis.
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: ["flask", "run"]
    volumes:
      - .:/srv 
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 5002:5002
    user: app

  worker:
    image: wildsong/accela-flask:latest
    environment:
      - PYTHONPATH=/srv
      # without these, celery tries to connect to RabbitMQ instead of REDIS.
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: celery --app=celery_worker worker --loglevel=info
    volumes:
      - .:/srv
    user: app

  monitor:
    image: wildsong/celery-monitor:latest
    build:
      context: .
      dockerfile: Dockerfile.monitor
    environment:
      - PYTHONPATH=/srv
      # without these, defaults to localhost.
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: flower -A celery_worker
    volumes:
      - .:/srv
    ports: 
      - 5555:5555
    user: app

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
#      start_period: 30s

